### ISSUE TITLE
MC sampling gets stuck

### ISSUE THREAD

**Issue by nielsenmb** [ashleychontos/pySYD#29]
I'm trying to run pySYD on a few Kepler targets, but when running with the --mc 200 option the sampler appears to get stuck at during the sampling, while for other stars it runs flawlessly. It doesn't crash, just hangs indefinitely. 

The initial parts of the run seem to work fine and output is produced, it only hangs when it gets to the sampling. 

Running on the same target multiple times, the sampler appears to get stuck at different times.

It's not entirely clear to me how the sampling is done, but I know in EMCEE something like this might occur if the sampler gets stuck beyond the bounds of a fit. Perhaps something like that is happening here?

It doesn't appear to be a memory issue, since the ones that get stuck appear to be shorter time series. 

I used the pip installable version of pySYD.

Examples:

pysyd run --star KIC4646780 --info info/star_info.csv --mc 200 -vto

------------------------------------------------------
Target: KIC4646780
------------------------------------------------------
# LIGHT CURVE: 43076 lines of data read
# Time series cadence: 59 seconds
# POWER SPECTRUM: 21677 lines of data read
# PS is critically-sampled
# PS resolution: 0.391961 muHz
------------------------------------------------------
Estimating numax:
PS binned to 195 datapoints
Numax estimate 1: 1040.94 +/- 18.96
S/N: 2.42
Numax estimate 2: 1085.80 +/- 35.76
S/N: 2.39
Numax estimate 3: 1179.34 +/- 61.26
S/N: 1.50
Selecting model 1
------------------------------------------------------
Determining background model:
PS binned to 424 data points
Comparing 6 different models:
Model 0: 0 Harvey-like component(s) + white noise fixed
Model 1: 0 Harvey-like component(s) + white noise term
Model 2: 1 Harvey-like component(s) + white noise fixed
Model 3: 1 Harvey-like component(s) + white noise term
Model 4: 2 Harvey-like component(s) + white noise fixed
Model 5: 2 Harvey-like component(s) + white noise term
Based on BIC statistic: model 4
 **background-corrected PS saved**
------------------------------------------------------
Running sampling routine:
 12%|█▎        | 24/200 [00:02<00:19,  8.95it/s]
 18%|█▊        | 36/200 [00:04<00:19,  8.50it/s]

pysyd run --star KIC1435467 --info info/star_info.csv --mc 200 -vto

Target: KIC1435467
------------------------------------------------------
# LIGHT CURVE: 486239 lines of data read
# Time series cadence: 59 seconds
# POWER SPECTRUM: 247854 lines of data read
# PS is critically-sampled
# PS resolution: 0.034280 muHz
------------------------------------------------------
Estimating numax:
PS binned to 195 datapoints
Numax estimate 1: 1445.36 +/- 85.66
S/N: 8.81
Numax estimate 2: 1455.28 +/- 93.08
S/N: 30.95
Numax estimate 3: 1481.68 +/- 103.31
S/N: 100.00
Selecting model 3
------------------------------------------------------
Determining background model:
PS binned to 424 data points
Comparing 6 different models:
Model 0: 0 Harvey-like component(s) + white noise fixed
Model 1: 0 Harvey-like component(s) + white noise term
Model 2: 1 Harvey-like component(s) + white noise fixed
Model 3: 1 Harvey-like component(s) + white noise term
Model 4: 2 Harvey-like component(s) + white noise fixed
Model 5: 2 Harvey-like component(s) + white noise term
Based on BIC statistic: model 4
 **background-corrected PS saved**
------------------------------------------------------
Running sampling routine:
 11%|█         | 22/200 [00:16<02:26,  1.22it/s]
 21%|██        | 42/200 [00:33<02:10,  1.21it/s]
 31%|███       | 62/200 [00:49<01:55,  1.21it/s]
 40%|████      | 81/200 [01:05<01:39,  1.20it/s]
 50%|████▉     | 99/200 [01:21<01:23,  1.22it/s]
 58%|█████▊    | 116/200 [01:35<01:09,  1.21it/s]
 67%|██████▋   | 133/200 [01:49<00:55,  1.21it/s]
 75%|███████▌  | 150/200 [02:03<00:41,  1.20it/s]
 84%|█████�██▎ | 166/200 [02:16<00:28,  1.21it/s]
 92%|████��
 99%|█████████▉| 198/200 [02:42<00:02,  1.21it/s]
100%|██████████| 200/200 [02:44<00:00,  1.21it/s]

Output parameters:
tau_1: 322.37 +/- 22.77 s
sigma_1: 53.03 +/- 2.68 ppm
tau_2: 112.21 +/- 12.13 s
sigma_2: 45.31 +/- 3.47 ppm
numax_smooth: 1388.91 +/- 11.23 muHz
A_smooth: 0.75 +/- 0.04 ppm^2/muHz
numax_gauss: 1425.56 +/- 11.67 muHz
A_gauss: 0.68 +/- 0.03 ppm^2/muHz
FWHM: 250.91 +/- 13.64 muHz
dnu: 70.48 +/- 0.11 muHz
------------------------------------------------------
----------------------------------------------------

TESTING INFORMATION:
362/424 points are being used for background fit

    ----------------------------------------------
    ------------- MODEL COMPARISONS --------------
    ----------------------------------------------
   Model 0: 0 Harvey-like component(s) + white noise fixed
    BIC = 408540.44 | AIC = 1128.56
   Model 1: 0 Harvey-like component(s) + white noise term
    BIC = 408502.55 | AIC = 1128.45
   Model 2: 1 Harvey-like component(s) + white noise fixed
    BIC = 402832.79 | AIC = 1112.78
   Model 3: 1 Harvey-like component(s) + white noise term
    BIC = 402819.23 | AIC = 1112.73
   Model 4: 2 Harvey-like component(s) + white noise fixed
    BIC = 402375.08 | AIC = 1111.49
   Model 5: 2 Harvey-like component(s) + white noise term
    BIC = 402388.49 | AIC = 1111.52
------------------------------------------------------ 
The power spectrum mask includes 36370 data points 
 i.e. the power excess region ~[858.33,2105.04]
 D method to estimate dnu ~= 70.34

 Median of ED: 51.64 
 Clip value of ED: 206.58
 M method to estimate dnu ~= 70.31
 A method to estimate dnu ~= 70.34
 D method to estimate dnu ~= 70.34
 - combining results into single csv file
------------------------------------------------------

**Comment by ashleychontos** [comment]
Hi Martin,

Thanks for all this information! Do you think you might be able to provide the time series and power spectrum so that I can recreate the issue from my end and look into it?

I think based on the output alone of the progress bar (which I’ve never seen like this before), it must be something related to bounds as you said. I’m happy to look into this and/or run the few Kepler stars from my end so I can feel like I’m contributing something from my end for the paper! No worries either way but definitely having the power spectrum for this particular star would be a good starting place for me.

Cheers,

Ashley

**Comment by nielsenmb** [comment]
Here's the PS and LC of one of the targets that stalled during the sampling. 

[KIC4646780_PS.txt](https://github.com/ashleychontos/pySYD/files/7138184/KIC4646780_PS.txt)
[KIC4646780_LC.txt](https://github.com/ashleychontos/pySYD/files/7138185/KIC4646780_LC.txt)

We're using the KASOC concatenated light curves so if you need more examples it might be better if I send you a list and you download them from there. If you don't already have access you just need to register and then you can download them. 

I was running with a radius and Teff prior (for KIC4646780 R=1.85\pm0.19R0, Teff=6856\pm138K), but I've tried turning them off and some targets still stalled.

**Comment by ashleychontos** [comment]
so I am trying to reproduce this error and having a hard time but I think I know why. Actually, it could be a couple things. The `-t` flag you are using was a development flag and shouldn't be used with `pysyd.run`. This was an oversight on my behalf in this release and has since been changed in the more recent versions. 

I've also attached the output figures for KIC4646780 and it looks like it's a very low S/N case. By using a lot of our optional features and a little brute force action, I was able to get the sampling to run for KIC4646780 no problem! **FWIW**: there will be a minor error at the end because of the letters in the name (e.g., "KIC"), which used to sort by integers -- but that won't affect the results or the outputs saved. I hope this helps!

Attached is the command I used:
<img width="787" alt="Screen Shot 2022-03-30 at 6 32 24 PM" src="https://user-images.githubusercontent.com/13820495/160941916-ff5b3e8f-1da3-4a1e-852b-ed7eda760fa7.png">
^^ the `-a` flag allows you to select which trial from the first module (estimate numax) you would like to use (see below)

<img width="790" alt="Screen Shot 2022-03-30 at 6 33 33 PM" src="https://user-images.githubusercontent.com/13820495/160942035-6c3ddae0-737e-42ff-bf81-350bf8142d2e.png">


![estimate_numax](https://user-images.githubusercontent.com/13820495/160942162-61618cc0-013e-4ea6-852a-38fd9f0fae15.png)

![global_fit](https://user-images.githubusercontent.com/13820495/160942198-e36f77f9-1b34-4e13-834c-ecbd5ac87dc7.png)

![samples](https://user-images.githubusercontent.com/13820495/160942242-038184c5-76f9-4c3f-916a-8b61a8eea1d1.png)
