### ISSUE TITLE
Problem with input files

### ISSUE THREAD

**Issue by Anohita1** [ashleychontos/pySYD#48]
------
I downloaded normalized lightcurves and power spectrum using lightkurve of one object KIC3441157 which is expected to have nu_max = 5-6 microHertz and del_nu = 1 microhertz (from literature)

Running this is giving me following error - AttributeError: module 'pysyd.utils' has no attribute 'PySYDInputError'
![Screenshot from 2023-04-30 00-00-25](https://user-images.githubusercontent.com/101514499/235318792-d71650f0-4d26-4ba1-96d5-916338fa82a0.png)
![Screenshot from 2023-04-30 00-00-36](https://user-images.githubusercontent.com/101514499/235318796-50d136f4-2460-4236-b8d6-806e9aa3c6fc.png)

 - **OS:** [Linux]
 - **Version:** [Ubuntu 20.04.6 LTS]
 - **Implementation:** [command line]

### Attachments
Lightcurve and power spectra files - obtained using lightkurve
[3441157_LC.txt](https://github.com/ashleychontos/pySYD/files/11359862/3441157_LC.txt)
[3441157_PS.txt](https://github.com/ashleychontos/pySYD/files/11359863/3441157_PS.txt)

### Other

------

## Summary Checklist:

- How were you using `pySYD` when you experienced the issue? command line from terminal
- Did you provide all the relevant information and files so that we can reproduce the error? Yes
- Did you check if the issue has already been reported? Yes &rightarrow; Was there a proposed workaround or solution? No
- Do you know if the issue is version specific? IDK
- Have you identified a workaround or solution? No
- Will you be submitting a pull request associated with this issue? No

------

**Comment by ashleychontos** [comment]
hi @Anohita1, thank you for bringing this to my attention. can you tell me what version you are using? I think this was a previous error but was fixed in more recent versions. Also please keep in mind that most of the parameters are optimized for a wide range of stars (i.e. not the best for much more evolved stars). For example, you can see that the power spectrum is binned to 5 points, which is not very helpful in any type of analysis. I would recommend to look at some of the additional command-line options to help fix that -- it might make other things work more smoothly.
